import { client, loadSettings, loadHotspots, loadNeighborhoods } from '../neon-client.js';
const ADMIN_EMAIL='sanmigueldeallendetech@gmail.com';
const loginView=document.getElementById('loginView'), dashboard=document.getElementById('dashboard'), loginForm=document.getElementById('loginForm'), loginError=document.getElementById('loginError');
let state={hotspots:[],barrios:[],settings:{},user:null};
const fallbackMessages={tech:'¡Hola! 👋 Necesito ayuda con un servicio de tecnología en San Miguel de Allende. ¿Me pueden ayudar? 💻\n\n[TECH]',art:'¡Hola! 👋 Estoy buscando información relacionada con arte en San Miguel de Allende. ¿Me pueden ayudar? 🎨\n\n[ART]',bodas:'¡Hola! 👋 Estoy buscando información sobre fotografía para mi boda en San Miguel de Allende. Me gustaría conocer las opciones disponibles. 💍📸\n\n[BODAS]',eventos:'¡Hola! 👋 Necesito ayuda con un servicio para un evento en San Miguel de Allende. ¿Me pueden ayudar? ✨\n\n[EVENTOS]',hogar:'¡Hola! 👋 Necesito ayuda con un servicio para el hogar en San Miguel de Allende. ¿Me pueden ayudar? 🏠\n\n[HOGAR]',realty:'¡Hola! 👋 Estoy buscando información sobre una propiedad en San Miguel de Allende. ¿Me pueden ayudar? 🏡\n\n[REALTY]'};

async function start(){
  try{const r=await client.auth.getSession(); const user=r.data?.user||r.data?.session?.user; if(user?.email===ADMIN_EMAIL) return openDashboard(user)}catch(e){}
  showLogin();
}
function showLogin(){loginView.hidden=false;dashboard.hidden=true}
async function openDashboard(user){state.user=user;loginView.hidden=true;dashboard.hidden=false;document.getElementById('userEmail').textContent=user.email;await reloadAll();bindTabs()}
loginForm.addEventListener('submit',async e=>{e.preventDefault();loginError.textContent='';const email=document.getElementById('email').value.trim().toLowerCase();const password=document.getElementById('password').value;if(email!==ADMIN_EMAIL){loginError.textContent='Acceso no autorizado.';return}const result=await client.auth.signIn.email({email,password,rememberMe:true});if(result.error){loginError.textContent='Correo o contraseña incorrectos.';return}const session=await client.auth.getSession();const user=session.data?.user||session.data?.session?.user;if(user?.email!==ADMIN_EMAIL){await client.auth.signOut();loginError.textContent='Acceso no autorizado.';return}openDashboard(user)});
document.getElementById('logoutBtn').onclick=async()=>{await client.auth.signOut();location.reload()};
function bindTabs(){document.querySelectorAll('[data-tab]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===btn.dataset.tab));document.getElementById('tabTitle').textContent=btn.textContent})}
async function reloadAll(){const [h,b,s]=await Promise.all([loadHotspots(true),loadNeighborhoods(),loadSettings()]);state.hotspots=h;state.barrios=b;state.settings=s;renderHotspots();renderBarrios();fillSettings();document.getElementById('statHotspots').textContent=h.length;document.getElementById('statBarrios').textContent=b.length}
function renderHotspots(filter=''){const box=document.getElementById('hotspotRows');const q=filter.toLowerCase();box.innerHTML=state.hotspots.filter(h=>!q||h.name.toLowerCase().includes(q)||(h.neighborhood||'').toLowerCase().includes(q)).map(h=>`<div class="row ${h.is_active?'':'muted'}" data-id="${h.id}"><div><strong>${esc(h.name)}</strong><span>${esc(h.neighborhood||h.category||'')}</span></div><span>${h.is_active?'●':'○'}</span></div>`).join('');box.querySelectorAll('.row').forEach(el=>el.onclick=()=>editHotspot(Number(el.dataset.id)))}
document.getElementById('hotspotSearch').oninput=e=>renderHotspots(e.target.value);
document.getElementById('newHotspot').onclick=()=>fillHotspot({id:'',name:'',category:'negocio',neighborhood:'Centro',latitude:20.9144,longitude:-100.745,description:'',url:'',image_url:'',sort_order:state.hotspots.length,is_active:true});
function editHotspot(id){const h=state.hotspots.find(x=>x.id===id);if(h)fillHotspot(h)}
function fillHotspot(h){qs('hotspotId').value=h.id||'';qs('hsName').value=h.name||'';qs('hsCategory').value=h.category||'';qs('hsNeighborhood').value=h.neighborhood||'';qs('hsLat').value=h.latitude??'';qs('hsLng').value=h.longitude??'';qs('hsDescription').value=h.description||'';qs('hsUrl').value=h.url||'';qs('hsImage').value=h.image_url||'';qs('hsOrder').value=h.sort_order??0;qs('hsActive').checked=h.is_active!==false}
document.getElementById('hotspotForm').onsubmit=async e=>{e.preventDefault();const id=qs('hotspotId').value;const payload={name:qs('hsName').value.trim(),category:qs('hsCategory').value.trim(),neighborhood:qs('hsNeighborhood').value.trim(),latitude:Number(qs('hsLat').value),longitude:Number(qs('hsLng').value),description:qs('hsDescription').value.trim(),url:qs('hsUrl').value.trim(),image_url:qs('hsImage').value.trim(),sort_order:Number(qs('hsOrder').value||0),is_active:qs('hsActive').checked,updated_at:new Date().toISOString()};let res;if(id)res=await client.from('map_hotspots').update(payload).eq('id',Number(id)).select();else res=await client.from('map_hotspots').insert({...payload,external_id:`cms_${Date.now()}`}).select();if(res.error)return alert(res.error.message);await reloadAll();if(res.data?.[0])fillHotspot(res.data[0]);flash('Guardado')};
document.getElementById('deleteHotspot').onclick=async()=>{const id=qs('hotspotId').value;if(!id)return;const res=await client.from('map_hotspots').update({is_active:false,updated_at:new Date().toISOString()}).eq('id',Number(id));if(res.error)return alert(res.error.message);await reloadAll();flash('Punto oculto')};
function renderBarrios(){const box=qs('barrioRows');box.innerHTML=state.barrios.map(b=>`<div class="row" data-id="${b.id}"><div><strong>${esc(b.name)}</strong><span>${b.is_active?'Publicado':'Oculto'}</span></div><span>↗</span></div>`).join('');box.querySelectorAll('.row').forEach(el=>el.onclick=()=>editBarrio(Number(el.dataset.id)));if(state.barrios[0]&&!qs('barrioId').value)editBarrio(state.barrios[0].id)}
function editBarrio(id){const b=state.barrios.find(x=>x.id===id);if(!b)return;qs('barrioId').value=b.id;qs('bName').value=b.name||'';qs('bDescription').value=b.description||'';qs('bStrengths').value=(b.geojson?.strengths||[]).join('\n');qs('bWeaknesses').value=(b.geojson?.weaknesses||[]).join('\n');qs('bActive').checked=b.is_active!==false}
document.getElementById('barrioForm').onsubmit=async e=>{e.preventDefault();const id=Number(qs('barrioId').value);const current=state.barrios.find(x=>x.id===id)||{};const meta={...(current.geojson||{}),strengths:lines(qs('bStrengths').value),weaknesses:lines(qs('bWeaknesses').value)};const res=await client.from('neighborhoods').update({name:qs('bName').value.trim(),description:qs('bDescription').value.trim(),geojson:meta,is_active:qs('bActive').checked,updated_at:new Date().toISOString()}).eq('id',id).select();if(res.error)return alert(res.error.message);await reloadAll();flash('Colonia guardada')};
function fillSettings(){const s=state.settings;qs('heroEyebrow').value=s.hero_eyebrow||'SAN MIGUEL DE ALLENDE · GUANAJUATO';qs('heroTitle1').value=s.hero_title_line1||'Servicios en';qs('heroTitle2').value=s.hero_title_line2||'San Miguel de Allende.';qs('heroLead').value=s.hero_lead||'Tecnología, arte, bodas, eventos, hogar y servicios inmobiliarios. Una sola entrada para encontrar la ruta correcta y continuar directamente por WhatsApp.';qs('sitePhone').value=s.whatsapp_phone||'447915374776';qs('siteCity').value=s.city||'San Miguel de Allende';const m={...fallbackMessages,...(s.whatsapp_messages||{})};document.querySelectorAll('[data-message]').forEach(t=>t.value=m[t.dataset.message]||'')}
document.getElementById('siteForm').onsubmit=async e=>{e.preventDefault();await saveSetting('hero_eyebrow',qs('heroEyebrow').value.trim());await saveSetting('hero_title_line1',qs('heroTitle1').value.trim());await saveSetting('hero_title_line2',qs('heroTitle2').value.trim());await saveSetting('hero_lead',qs('heroLead').value.trim());await saveSetting('whatsapp_phone',qs('sitePhone').value.trim());await saveSetting('city',qs('siteCity').value.trim());await reloadAll();flash('Sitio actualizado')};
document.getElementById('whatsappForm').onsubmit=async e=>{e.preventDefault();const value={};document.querySelectorAll('[data-message]').forEach(t=>value[t.dataset.message]=t.value);await saveSetting('whatsapp_messages',value);await reloadAll();flash('Mensajes actualizados')};
async function saveSetting(key,value){const exists=Object.prototype.hasOwnProperty.call(state.settings,key);const res=exists?await client.from('site_settings').update({value,updated_at:new Date().toISOString()}).eq('key',key):await client.from('site_settings').insert({key,value});if(res.error)throw res.error}
function flash(t){const el=qs('saveState');if(el){el.textContent=t;setTimeout(()=>el.textContent='',1800)}}function qs(id){return document.getElementById(id)}function lines(s){return s.split('\n').map(x=>x.trim()).filter(Boolean)}function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
start();
